apiVersion: v1
kind: Service
metadata:
  name: go-hello-world-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 8080
  selector:
    app: go-hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-hello-world
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-hello-world-service
                port:
                  number: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      containers:
        - name: go-hello-world
          image: k3d-registry.localhost:5000/go-k8s:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
